import { PanoramaItem } from './models/panorama-item';

export const panoramaStaticSource: Array<PanoramaItem> = [
  {
    id: 1,
    title: 'pan2',
    paths: {
      left: './assets/panoramas/pan2/pano_0.jpg',
      front: './assets/panoramas/pan2/pano_1.jpg',
      right: './assets/panoramas/pan2/pano_2.jpg',
      back: './assets/panoramas/pan2/pano_3.jpg',
      top: './assets/panoramas/pan2/pano_4.jpg',
      bottom: './assets/panoramas/pan2/pano_5.jpg',
    },
  },
  {
    id: 2,
    title: 'panorama_Awawfagawa',
    paths: {
      left: './assets/panoramas/panorama_Awawfagawa/pano_0.jpg',
      front: './assets/panoramas/panorama_Awawfagawa/pano_1.jpg',
      right: './assets/panoramas/panorama_Awawfagawa/pano_2.jpg',
      back: './assets/panoramas/panorama_Awawfagawa/pano_3.jpg',
      top: './assets/panoramas/panorama_Awawfagawa/pano_4.jpg',
      bottom: './assets/panoramas/panorama_Awawfagawa/pano_5.jpg',
    },
  },
  {
    id: 3,
    title: '_MG_9408_Panorama',
    paths: {
      left: './assets/panoramas/_MG_9408_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_9408_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_9408_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_9408_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_9408_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_9408_Panorama/pano_5.jpg',
    },
  },
  {
    id: 4,
    title: 'pan3',
    paths: {
      left: './assets/panoramas/pan3/pano_0.jpg',
      front: './assets/panoramas/pan3/pano_1.jpg',
      right: './assets/panoramas/pan3/pano_2.jpg',
      back: './assets/panoramas/pan3/pano_3.jpg',
      top: './assets/panoramas/pan3/pano_4.jpg',
      bottom: './assets/panoramas/pan3/pano_5.jpg',
    },
  },
  {
    id: 5,
    title: 'pan4',
    paths: {
      left: './assets/panoramas/pan4/pano_0.jpg',
      front: './assets/panoramas/pan4/pano_1.jpg',
      right: './assets/panoramas/pan4/pano_2.jpg',
      back: './assets/panoramas/pan4/pano_3.jpg',
      top: './assets/panoramas/pan4/pano_4.jpg',
      bottom: './assets/panoramas/pan4/pano_5.jpg',
    },
  },
  {
    id: 6,
    title: 'gdm2011',
    paths: {
      left: './assets/panoramas/gdm2011/pano_0.jpg',
      front: './assets/panoramas/gdm2011/pano_1.jpg',
      right: './assets/panoramas/gdm2011/pano_2.jpg',
      back: './assets/panoramas/gdm2011/pano_3.jpg',
      top: './assets/panoramas/gdm2011/pano_4.jpg',
      bottom: './assets/panoramas/gdm2011/pano_5.jpg',
    },
  },
  {
    id: 7,
    title: 'pan3_afawfa',
    paths: {
      left: './assets/panoramas/pan3_afawfa/pano_0.jpg',
      front: './assets/panoramas/pan3_afawfa/pano_1.jpg',
      right: './assets/panoramas/pan3_afawfa/pano_2.jpg',
      back: './assets/panoramas/pan3_afawfa/pano_3.jpg',
      top: './assets/panoramas/pan3_afawfa/pano_4.jpg',
      bottom: './assets/panoramas/pan3_afawfa/pano_5.jpg',
    },
  },
  {
    id: 8,
    title: 'podwórko',
    paths: {
      left: './assets/panoramas/podwórko/pano_0.jpg',
      front: './assets/panoramas/podwórko/pano_1.jpg',
      right: './assets/panoramas/podwórko/pano_2.jpg',
      back: './assets/panoramas/podwórko/pano_3.jpg',
      top: './assets/panoramas/podwórko/pano_4.jpg',
      bottom: './assets/panoramas/podwórko/pano_5.jpg',
    },
  },
  {
    id: 9,
    title: 'pano_lighti',
    paths: {
      left: './assets/panoramas/pano_lighti/pano_0.jpg',
      front: './assets/panoramas/pano_lighti/pano_1.jpg',
      right: './assets/panoramas/pano_lighti/pano_2.jpg',
      back: './assets/panoramas/pano_lighti/pano_3.jpg',
      top: './assets/panoramas/pano_lighti/pano_4.jpg',
      bottom: './assets/panoramas/pano_lighti/pano_5.jpg',
    },
  },
  {
    id: 10,
    title: 'panorama1',
    paths: {
      left: './assets/panoramas/panorama1/pano_0.jpg',
      front: './assets/panoramas/panorama1/pano_1.jpg',
      right: './assets/panoramas/panorama1/pano_2.jpg',
      back: './assets/panoramas/panorama1/pano_3.jpg',
      top: './assets/panoramas/panorama1/pano_4.jpg',
      bottom: './assets/panoramas/panorama1/pano_5.jpg',
    },
  },
  {
    id: 11,
    title: '_MG_0173_Panorama',
    paths: {
      left: './assets/panoramas/_MG_0173_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_0173_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_0173_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_0173_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_0173_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_0173_Panorama/pano_5.jpg',
    },
  },
  {
    id: 12,
    title: 'Panorama_korytarz_hi_res',
    paths: {
      left: './assets/panoramas/Panorama_korytarz_hi_res/pano_0.jpg',
      front: './assets/panoramas/Panorama_korytarz_hi_res/pano_1.jpg',
      right: './assets/panoramas/Panorama_korytarz_hi_res/pano_2.jpg',
      back: './assets/panoramas/Panorama_korytarz_hi_res/pano_3.jpg',
      top: './assets/panoramas/Panorama_korytarz_hi_res/pano_4.jpg',
      bottom: './assets/panoramas/Panorama_korytarz_hi_res/pano_5.jpg',
    },
  },
  {
    id: 13,
    title: 'pan2_adaw',
    paths: {
      left: './assets/panoramas/pan2_adaw/pano_0.jpg',
      front: './assets/panoramas/pan2_adaw/pano_1.jpg',
      right: './assets/panoramas/pan2_adaw/pano_2.jpg',
      back: './assets/panoramas/pan2_adaw/pano_3.jpg',
      top: './assets/panoramas/pan2_adaw/pano_4.jpg',
      bottom: './assets/panoramas/pan2_adaw/pano_5.jpg',
    },
  },
  {
    id: 14,
    title: 'untitledadawafa',
    paths: {
      left: './assets/panoramas/untitledadawafa/pano_0.jpg',
      front: './assets/panoramas/untitledadawafa/pano_1.jpg',
      right: './assets/panoramas/untitledadawafa/pano_2.jpg',
      back: './assets/panoramas/untitledadawafa/pano_3.jpg',
      top: './assets/panoramas/untitledadawafa/pano_4.jpg',
      bottom: './assets/panoramas/untitledadawafa/pano_5.jpg',
    },
  },
  {
    id: 15,
    title: 'pano14',
    paths: {
      left: './assets/panoramas/pano14/pano_0.jpg',
      front: './assets/panoramas/pano14/pano_1.jpg',
      right: './assets/panoramas/pano14/pano_2.jpg',
      back: './assets/panoramas/pano14/pano_3.jpg',
      top: './assets/panoramas/pano14/pano_4.jpg',
      bottom: './assets/panoramas/pano14/pano_5.jpg',
    },
  },
  {
    id: 16,
    title: 'mini_9408_Panorama',
    paths: {
      left: './assets/panoramas/mini_9408_Panorama/pano_0.jpg',
      front: './assets/panoramas/mini_9408_Panorama/pano_1.jpg',
      right: './assets/panoramas/mini_9408_Panorama/pano_2.jpg',
      back: './assets/panoramas/mini_9408_Panorama/pano_3.jpg',
      top: './assets/panoramas/mini_9408_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/mini_9408_Panorama/pano_5.jpg',
    },
  },
  {
    id: 17,
    title: '_MG_9671_Panorama',
    paths: {
      left: './assets/panoramas/_MG_9671_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_9671_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_9671_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_9671_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_9671_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_9671_Panorama/pano_5.jpg',
    },
  },
  {
    id: 18,
    title: 'leba1',
    paths: {
      left: './assets/panoramas/leba1/pano_0.jpg',
      front: './assets/panoramas/leba1/pano_1.jpg',
      right: './assets/panoramas/leba1/pano_2.jpg',
      back: './assets/panoramas/leba1/pano_3.jpg',
      top: './assets/panoramas/leba1/pano_4.jpg',
      bottom: './assets/panoramas/leba1/pano_5.jpg',
    },
  },
  {
    id: 19,
    title: 'podgaje2011',
    paths: {
      left: './assets/panoramas/podgaje2011/pano_0.jpg',
      front: './assets/panoramas/podgaje2011/pano_1.jpg',
      right: './assets/panoramas/podgaje2011/pano_2.jpg',
      back: './assets/panoramas/podgaje2011/pano_3.jpg',
      top: './assets/panoramas/podgaje2011/pano_4.jpg',
      bottom: './assets/panoramas/podgaje2011/pano_5.jpg',
    },
  },
  {
    id: 20,
    title: 'untitled1',
    paths: {
      left: './assets/panoramas/untitled1/pano_0.jpg',
      front: './assets/panoramas/untitled1/pano_1.jpg',
      right: './assets/panoramas/untitled1/pano_2.jpg',
      back: './assets/panoramas/untitled1/pano_3.jpg',
      top: './assets/panoramas/untitled1/pano_4.jpg',
      bottom: './assets/panoramas/untitled1/pano_5.jpg',
    },
  },
  {
    id: 21,
    title: '_MG_9460_Panorama',
    paths: {
      left: './assets/panoramas/_MG_9460_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_9460_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_9460_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_9460_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_9460_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_9460_Panorama/pano_5.jpg',
    },
  },
  {
    id: 22,
    title: 'pan1',
    paths: {
      left: './assets/panoramas/pan1/pano_0.jpg',
      front: './assets/panoramas/pan1/pano_1.jpg',
      right: './assets/panoramas/pan1/pano_2.jpg',
      back: './assets/panoramas/pan1/pano_3.jpg',
      top: './assets/panoramas/pan1/pano_4.jpg',
      bottom: './assets/panoramas/pan1/pano_5.jpg',
    },
  },
  {
    id: 23,
    title: 'pokoj2',
    paths: {
      left: './assets/panoramas/pokoj2/pano_0.jpg',
      front: './assets/panoramas/pokoj2/pano_1.jpg',
      right: './assets/panoramas/pokoj2/pano_2.jpg',
      back: './assets/panoramas/pokoj2/pano_3.jpg',
      top: './assets/panoramas/pokoj2/pano_4.jpg',
      bottom: './assets/panoramas/pokoj2/pano_5.jpg',
    },
  },
  {
    id: 24,
    title: '_MG_9428_Panorama',
    paths: {
      left: './assets/panoramas/_MG_9428_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_9428_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_9428_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_9428_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_9428_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_9428_Panorama/pano_5.jpg',
    },
  },
  {
    id: 25,
    title: 'pakm',
    paths: {
      left: './assets/panoramas/pakm/pano_0.jpg',
      front: './assets/panoramas/pakm/pano_1.jpg',
      right: './assets/panoramas/pakm/pano_2.jpg',
      back: './assets/panoramas/pakm/pano_3.jpg',
      top: './assets/panoramas/pakm/pano_4.jpg',
      bottom: './assets/panoramas/pakm/pano_5.jpg',
    },
  },
  {
    id: 26,
    title: 'untitled0',
    paths: {
      left: './assets/panoramas/untitled0/pano_0.jpg',
      front: './assets/panoramas/untitled0/pano_1.jpg',
      right: './assets/panoramas/untitled0/pano_2.jpg',
      back: './assets/panoramas/untitled0/pano_3.jpg',
      top: './assets/panoramas/untitled0/pano_4.jpg',
      bottom: './assets/panoramas/untitled0/pano_5.jpg',
    },
  },
  {
    id: 27,
    title: 'piast',
    paths: {
      left: './assets/panoramas/piast/pano_0.jpg',
      front: './assets/panoramas/piast/pano_1.jpg',
      right: './assets/panoramas/piast/pano_2.jpg',
      back: './assets/panoramas/piast/pano_3.jpg',
      top: './assets/panoramas/piast/pano_4.jpg',
      bottom: './assets/panoramas/piast/pano_5.jpg',
    },
  },
  {
    id: 28,
    title: 'panorama',
    paths: {
      left: './assets/panoramas/panorama/pano_0.jpg',
      front: './assets/panoramas/panorama/pano_1.jpg',
      right: './assets/panoramas/panorama/pano_2.jpg',
      back: './assets/panoramas/panorama/pano_3.jpg',
      top: './assets/panoramas/panorama/pano_4.jpg',
      bottom: './assets/panoramas/panorama/pano_5.jpg',
    },
  },
  {
    id: 29,
    title: 'untitledawdawdaw',
    paths: {
      left: './assets/panoramas/untitledawdawdaw/pano_0.jpg',
      front: './assets/panoramas/untitledawdawdaw/pano_1.jpg',
      right: './assets/panoramas/untitledawdawdaw/pano_2.jpg',
      back: './assets/panoramas/untitledawdawdaw/pano_3.jpg',
      top: './assets/panoramas/untitledawdawdaw/pano_4.jpg',
      bottom: './assets/panoramas/untitledawdawdaw/pano_5.jpg',
    },
  },
  {
    id: 30,
    title: 'rynekzlotow',
    paths: {
      left: './assets/panoramas/rynekzlotow/pano_0.jpg',
      front: './assets/panoramas/rynekzlotow/pano_1.jpg',
      right: './assets/panoramas/rynekzlotow/pano_2.jpg',
      back: './assets/panoramas/rynekzlotow/pano_3.jpg',
      top: './assets/panoramas/rynekzlotow/pano_4.jpg',
      bottom: './assets/panoramas/rynekzlotow/pano_5.jpg',
    },
  },
  {
    id: 31,
    title: 'pierwsza_panorama',
    paths: {
      left: './assets/panoramas/pierwsza_panorama/pano_0.jpg',
      front: './assets/panoramas/pierwsza_panorama/pano_1.jpg',
      right: './assets/panoramas/pierwsza_panorama/pano_2.jpg',
      back: './assets/panoramas/pierwsza_panorama/pano_3.jpg',
      top: './assets/panoramas/pierwsza_panorama/pano_4.jpg',
      bottom: './assets/panoramas/pierwsza_panorama/pano_5.jpg',
    },
  },
  {
    id: 32,
    title: 'untitled',
    paths: {
      left: './assets/panoramas/untitled/pano_0.jpg',
      front: './assets/panoramas/untitled/pano_1.jpg',
      right: './assets/panoramas/untitled/pano_2.jpg',
      back: './assets/panoramas/untitled/pano_3.jpg',
      top: './assets/panoramas/untitled/pano_4.jpg',
      bottom: './assets/panoramas/untitled/pano_5.jpg',
    },
  },
  {
    id: 33,
    title: 'plac_zabaw_duze_braki_w_obrazie',
    paths: {
      left: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_0.jpg',
      front: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_1.jpg',
      right: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_2.jpg',
      back: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_3.jpg',
      top: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_4.jpg',
      bottom: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_5.jpg',
    },
  },
  {
    id: 34,
    title: 'pan1_aw',
    paths: {
      left: './assets/panoramas/pan1_aw/pano_0.jpg',
      front: './assets/panoramas/pan1_aw/pano_1.jpg',
      right: './assets/panoramas/pan1_aw/pano_2.jpg',
      back: './assets/panoramas/pan1_aw/pano_3.jpg',
      top: './assets/panoramas/pan1_aw/pano_4.jpg',
      bottom: './assets/panoramas/pan1_aw/pano_5.jpg',
    },
  },
  {
    id: 35,
    title: 'eryk',
    paths: {
      left: './assets/panoramas/eryk/pano_0.jpg',
      front: './assets/panoramas/eryk/pano_1.jpg',
      right: './assets/panoramas/eryk/pano_2.jpg',
      back: './assets/panoramas/eryk/pano_3.jpg',
      top: './assets/panoramas/eryk/pano_4.jpg',
      bottom: './assets/panoramas/eryk/pano_5.jpg',
    },
  },
  {
    id: 36,
    title: 'Panorama_Salon_wersja_light',
    paths: {
      left: './assets/panoramas/Panorama_Salon_wersja_light/pano_0.jpg',
      front: './assets/panoramas/Panorama_Salon_wersja_light/pano_1.jpg',
      right: './assets/panoramas/Panorama_Salon_wersja_light/pano_2.jpg',
      back: './assets/panoramas/Panorama_Salon_wersja_light/pano_3.jpg',
      top: './assets/panoramas/Panorama_Salon_wersja_light/pano_4.jpg',
      bottom: './assets/panoramas/Panorama_Salon_wersja_light/pano_5.jpg',
    },
  },
  // {
  //   id: 37,
  //   title: 'untitled2a',
  //   paths: {
  //     left: './assets/panoramas/untitled2a/pano_0.jpg',
  //     front: './assets/panoramas/untitled2a/pano_1.jpg',
  //     right: './assets/panoramas/untitled2a/pano_2.jpg',
  //     back: './assets/panoramas/untitled2a/pano_3.jpg',
  //     top: './assets/panoramas/untitled2a/pano_4.jpg',
  //     bottom: './assets/panoramas/untitled2a/pano_5.jpg',
  //   },
  // },
  {
    id: 38,
    title: 'wersja_hi',
    paths: {
      left: './assets/panoramas/wersja_hi/pano_0.jpg',
      front: './assets/panoramas/wersja_hi/pano_1.jpg',
      right: './assets/panoramas/wersja_hi/pano_2.jpg',
      back: './assets/panoramas/wersja_hi/pano_3.jpg',
      top: './assets/panoramas/wersja_hi/pano_4.jpg',
      bottom: './assets/panoramas/wersja_hi/pano_5.jpg',
    },
  },
  {
    id: 39,
    title: 'Chaber',
    paths: {
      left: './assets/panoramas/Chaber/pano_0.jpg',
      front: './assets/panoramas/Chaber/pano_1.jpg',
      right: './assets/panoramas/Chaber/pano_2.jpg',
      back: './assets/panoramas/Chaber/pano_3.jpg',
      top: './assets/panoramas/Chaber/pano_4.jpg',
      bottom: './assets/panoramas/Chaber/pano_5.jpg',
    },
  },
];
