import { PanoramaItem } from './models/panorama-item';
import { PanoramaTypeEnum } from './models/panorama-type.enum';

export const panoramaStaticSource: Array<PanoramaItem> = [
  {
    id: 1,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pan2',
    caption: 'Maurycy - Piekary 2',
    paths: {
      left: './assets/panoramas/pan2/pano_0.jpg',
      front: './assets/panoramas/pan2/pano_1.jpg',
      right: './assets/panoramas/pan2/pano_2.jpg',
      back: './assets/panoramas/pan2/pano_3.jpg',
      top: './assets/panoramas/pan2/pano_4.jpg',
      bottom: './assets/panoramas/pan2/pano_5.jpg',
    },
  },
  // {
  //   id: 2,
  // type: PanoramaTypeEnum.cubeFaces,
  //   rawTitle: 'panorama_Awawfagawa',
  //   caption: 'OW Chaber',
  //   paths: {
  //     left: './assets/panoramas/panorama_Awawfagawa/pano_0.jpg',
  //     front: './assets/panoramas/panorama_Awawfagawa/pano_1.jpg',
  //     right: './assets/panoramas/panorama_Awawfagawa/pano_2.jpg',
  //     back: './assets/panoramas/panorama_Awawfagawa/pano_3.jpg',
  //     top: './assets/panoramas/panorama_Awawfagawa/pano_4.jpg',
  //     bottom: './assets/panoramas/panorama_Awawfagawa/pano_5.jpg',
  //   },
  // },
  {
    id: 3,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: '_MG_9408_Panorama',
    caption: 'GDM Scena setup 1',
    paths: {
      left: './assets/panoramas/_MG_9408_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_9408_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_9408_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_9408_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_9408_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_9408_Panorama/pano_5.jpg',
    },
  },
  {
    id: 4,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pan3',
    caption: 'Maurycy - Piekary 3',
    paths: {
      left: './assets/panoramas/pan3/pano_0.jpg',
      front: './assets/panoramas/pan3/pano_1.jpg',
      right: './assets/panoramas/pan3/pano_2.jpg',
      back: './assets/panoramas/pan3/pano_3.jpg',
      top: './assets/panoramas/pan3/pano_4.jpg',
      bottom: './assets/panoramas/pan3/pano_5.jpg',
    },
  },
  {
    id: 5,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pan4',
    caption: 'Maurycy - Piekary 4',
    paths: {
      left: './assets/panoramas/pan4/pano_0.jpg',
      front: './assets/panoramas/pan4/pano_1.jpg',
      right: './assets/panoramas/pan4/pano_2.jpg',
      back: './assets/panoramas/pan4/pano_3.jpg',
      top: './assets/panoramas/pan4/pano_4.jpg',
      bottom: './assets/panoramas/pan4/pano_5.jpg',
    },
  },
  {
    id: 6,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'gdm2011',
    caption: 'GDM 2011 Mateo Salka',
    paths: {
      left: './assets/panoramas/gdm2011/pano_0.jpg',
      front: './assets/panoramas/gdm2011/pano_1.jpg',
      right: './assets/panoramas/gdm2011/pano_2.jpg',
      back: './assets/panoramas/gdm2011/pano_3.jpg',
      top: './assets/panoramas/gdm2011/pano_4.jpg',
      bottom: './assets/panoramas/gdm2011/pano_5.jpg',
    },
  },
  {
    id: 7,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pan3_afawfa',
    caption: 'OW Chaber - Blaszak',
    paths: {
      left: './assets/panoramas/pan3_afawfa/pano_0.jpg',
      front: './assets/panoramas/pan3_afawfa/pano_1.jpg',
      right: './assets/panoramas/pan3_afawfa/pano_2.jpg',
      back: './assets/panoramas/pan3_afawfa/pano_3.jpg',
      top: './assets/panoramas/pan3_afawfa/pano_4.jpg',
      bottom: './assets/panoramas/pan3_afawfa/pano_5.jpg',
    },
  },
  {
    id: 8,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'podworko',
    caption: 'Podwórko',
    paths: {
      left: './assets/panoramas/podworko/pano_0.jpg',
      front: './assets/panoramas/podworko/pano_1.jpg',
      right: './assets/panoramas/podworko/pano_2.jpg',
      back: './assets/panoramas/podworko/pano_3.jpg',
      top: './assets/panoramas/podworko/pano_4.jpg',
      bottom: './assets/panoramas/podworko/pano_5.jpg',
    },
  },
  {
    id: 9,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pano_lighti',
    caption: 'BS - katakumby',
    paths: {
      left: './assets/panoramas/pano_lighti/pano_0.jpg',
      front: './assets/panoramas/pano_lighti/pano_1.jpg',
      right: './assets/panoramas/pano_lighti/pano_2.jpg',
      back: './assets/panoramas/pano_lighti/pano_3.jpg',
      top: './assets/panoramas/pano_lighti/pano_4.jpg',
      bottom: './assets/panoramas/pano_lighti/pano_5.jpg',
    },
  },
  // {
  //   id: 10,
  // type: PanoramaTypeEnum.cubeFaces,
  //   rawTitle: 'panorama1',
  //   caption: 'Pierwsza panorama',
  //   paths: {
  //     left: './assets/panoramas/panorama1/pano_0.jpg',
  //     front: './assets/panoramas/panorama1/pano_1.jpg',
  //     right: './assets/panoramas/panorama1/pano_2.jpg',
  //     back: './assets/panoramas/panorama1/pano_3.jpg',
  //     top: './assets/panoramas/panorama1/pano_4.jpg',
  //     bottom: './assets/panoramas/panorama1/pano_5.jpg',
  //   },
  // },
  {
    id: 11,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: '_MG_0173_Panorama',
    caption: 'Pokój poddasze',
    paths: {
      left: './assets/panoramas/_MG_0173_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_0173_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_0173_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_0173_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_0173_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_0173_Panorama/pano_5.jpg',
    },
  },
  {
    id: 12,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'Panorama_korytarz_hi_res',
    caption: 'BS - korytarz',
    paths: {
      left: './assets/panoramas/Panorama_korytarz_hi_res/pano_0.jpg',
      front: './assets/panoramas/Panorama_korytarz_hi_res/pano_1.jpg',
      right: './assets/panoramas/Panorama_korytarz_hi_res/pano_2.jpg',
      back: './assets/panoramas/Panorama_korytarz_hi_res/pano_3.jpg',
      top: './assets/panoramas/Panorama_korytarz_hi_res/pano_4.jpg',
      bottom: './assets/panoramas/Panorama_korytarz_hi_res/pano_5.jpg',
    },
  },
  {
    id: 13,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pan2_adaw',
    caption: 'OW Chaber - Blaszak (krzywo)',
    paths: {
      left: './assets/panoramas/pan2_adaw/pano_0.jpg',
      front: './assets/panoramas/pan2_adaw/pano_1.jpg',
      right: './assets/panoramas/pan2_adaw/pano_2.jpg',
      back: './assets/panoramas/pan2_adaw/pano_3.jpg',
      top: './assets/panoramas/pan2_adaw/pano_4.jpg',
      bottom: './assets/panoramas/pan2_adaw/pano_5.jpg',
    },
  },
  {
    id: 14,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'untitledadawafa',
    caption: 'GDM Scena setup 2',
    paths: {
      left: './assets/panoramas/untitledadawafa/pano_0.jpg',
      front: './assets/panoramas/untitledadawafa/pano_1.jpg',
      right: './assets/panoramas/untitledadawafa/pano_2.jpg',
      back: './assets/panoramas/untitledadawafa/pano_3.jpg',
      top: './assets/panoramas/untitledadawafa/pano_4.jpg',
      bottom: './assets/panoramas/untitledadawafa/pano_5.jpg',
    },
  },
  {
    id: 15,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pano14',
    caption: 'OW Chaber - Blaszak (no watermark)',
    paths: {
      left: './assets/panoramas/pano14/pano_0.jpg',
      front: './assets/panoramas/pano14/pano_1.jpg',
      right: './assets/panoramas/pano14/pano_2.jpg',
      back: './assets/panoramas/pano14/pano_3.jpg',
      top: './assets/panoramas/pano14/pano_4.jpg',
      bottom: './assets/panoramas/pano14/pano_5.jpg',
    },
  },
  // {
  //   id: 16,
  // type: PanoramaTypeEnum.cubeFaces,
  //   rawTitle: 'mini_9408_Panorama',
  //   paths: {
  //     left: './assets/panoramas/mini_9408_Panorama/pano_0.jpg',
  //     front: './assets/panoramas/mini_9408_Panorama/pano_1.jpg',
  //     right: './assets/panoramas/mini_9408_Panorama/pano_2.jpg',
  //     back: './assets/panoramas/mini_9408_Panorama/pano_3.jpg',
  //     top: './assets/panoramas/mini_9408_Panorama/pano_4.jpg',
  //     bottom: './assets/panoramas/mini_9408_Panorama/pano_5.jpg',
  //   },
  // },
  {
    id: 17,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: '_MG_9671_Panorama',
    caption: 'Podgaje 2011',
    paths: {
      left: './assets/panoramas/_MG_9671_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_9671_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_9671_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_9671_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_9671_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_9671_Panorama/pano_5.jpg',
    },
  },
  {
    id: 18,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'leba1',
    caption: 'Łeba - plaza',
    paths: {
      left: './assets/panoramas/leba1/pano_0.jpg',
      front: './assets/panoramas/leba1/pano_1.jpg',
      right: './assets/panoramas/leba1/pano_2.jpg',
      back: './assets/panoramas/leba1/pano_3.jpg',
      top: './assets/panoramas/leba1/pano_4.jpg',
      bottom: './assets/panoramas/leba1/pano_5.jpg',
    },
  },
  // {
  //   id: 19,
  // type: PanoramaTypeEnum.cubeFaces,
  //   rawTitle: 'podgaje2011',
  //   paths: {
  //     left: './assets/panoramas/podgaje2011/pano_0.jpg',
  //     front: './assets/panoramas/podgaje2011/pano_1.jpg',
  //     right: './assets/panoramas/podgaje2011/pano_2.jpg',
  //     back: './assets/panoramas/podgaje2011/pano_3.jpg',
  //     top: './assets/panoramas/podgaje2011/pano_4.jpg',
  //     bottom: './assets/panoramas/podgaje2011/pano_5.jpg',
  //   },
  // },
  {
    id: 20,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'untitled1',
    caption: 'Lębork 2010',
    paths: {
      left: './assets/panoramas/untitled1/pano_0.jpg',
      front: './assets/panoramas/untitled1/pano_1.jpg',
      right: './assets/panoramas/untitled1/pano_2.jpg',
      back: './assets/panoramas/untitled1/pano_3.jpg',
      top: './assets/panoramas/untitled1/pano_4.jpg',
      bottom: './assets/panoramas/untitled1/pano_5.jpg',
    },
  },
  {
    id: 21,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: '_MG_9460_Panorama',
    caption: 'GDM 2021 - pusta salka',
    paths: {
      left: './assets/panoramas/_MG_9460_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_9460_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_9460_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_9460_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_9460_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_9460_Panorama/pano_5.jpg',
    },
  },
  {
    id: 22,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pan1',
    caption: 'Maurycy - Piekary 1',
    paths: {
      left: './assets/panoramas/pan1/pano_0.jpg',
      front: './assets/panoramas/pan1/pano_1.jpg',
      right: './assets/panoramas/pan1/pano_2.jpg',
      back: './assets/panoramas/pan1/pano_3.jpg',
      top: './assets/panoramas/pan1/pano_4.jpg',
      bottom: './assets/panoramas/pan1/pano_5.jpg',
    },
  },
  {
    id: 23,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pokoj2',
    caption: 'Pokój Bartosz',
    paths: {
      left: './assets/panoramas/pokoj2/pano_0.jpg',
      front: './assets/panoramas/pokoj2/pano_1.jpg',
      right: './assets/panoramas/pokoj2/pano_2.jpg',
      back: './assets/panoramas/pokoj2/pano_3.jpg',
      top: './assets/panoramas/pokoj2/pano_4.jpg',
      bottom: './assets/panoramas/pokoj2/pano_5.jpg',
    },
  },
  {
    id: 24,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: '_MG_9428_Panorama',
    caption: 'GDM 2011 - przed sceną',
    paths: {
      left: './assets/panoramas/_MG_9428_Panorama/pano_0.jpg',
      front: './assets/panoramas/_MG_9428_Panorama/pano_1.jpg',
      right: './assets/panoramas/_MG_9428_Panorama/pano_2.jpg',
      back: './assets/panoramas/_MG_9428_Panorama/pano_3.jpg',
      top: './assets/panoramas/_MG_9428_Panorama/pano_4.jpg',
      bottom: './assets/panoramas/_MG_9428_Panorama/pano_5.jpg',
    },
  },
  {
    id: 25,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pakm',
    caption: 'Poznań - Aleje Marcinkowskiego',
    paths: {
      left: './assets/panoramas/pakm/pano_0.jpg',
      front: './assets/panoramas/pakm/pano_1.jpg',
      right: './assets/panoramas/pakm/pano_2.jpg',
      back: './assets/panoramas/pakm/pano_3.jpg',
      top: './assets/panoramas/pakm/pano_4.jpg',
      bottom: './assets/panoramas/pakm/pano_5.jpg',
    },
  },
  {
    id: 26,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'untitled0',
    caption: 'GDM 2011 - setup 3',
    paths: {
      left: './assets/panoramas/untitled0/pano_0.jpg',
      front: './assets/panoramas/untitled0/pano_1.jpg',
      right: './assets/panoramas/untitled0/pano_2.jpg',
      back: './assets/panoramas/untitled0/pano_3.jpg',
      top: './assets/panoramas/untitled0/pano_4.jpg',
      bottom: './assets/panoramas/untitled0/pano_5.jpg',
    },
  },
  {
    id: 27,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'piast',
    caption: 'Złotów - Al. Piasta',
    paths: {
      left: './assets/panoramas/piast/pano_0.jpg',
      front: './assets/panoramas/piast/pano_1.jpg',
      right: './assets/panoramas/piast/pano_2.jpg',
      back: './assets/panoramas/piast/pano_3.jpg',
      top: './assets/panoramas/piast/pano_4.jpg',
      bottom: './assets/panoramas/piast/pano_5.jpg',
    },
  },
  // {
  //   id: 28,
  // type: PanoramaTypeEnum.cubeFaces,
  //   rawTitle: 'panorama',
  //   paths: {
  //     left: './assets/panoramas/panorama/pano_0.jpg',
  //     front: './assets/panoramas/panorama/pano_1.jpg',
  //     right: './assets/panoramas/panorama/pano_2.jpg',
  //     back: './assets/panoramas/panorama/pano_3.jpg',
  //     top: './assets/panoramas/panorama/pano_4.jpg',
  //     bottom: './assets/panoramas/panorama/pano_5.jpg',
  //   },
  // },
  {
    id: 29,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'untitledawdawdaw',
    caption: 'Poznań - Stary Rynek',
    paths: {
      left: './assets/panoramas/untitledawdawdaw/pano_0.jpg',
      front: './assets/panoramas/untitledawdawdaw/pano_1.jpg',
      right: './assets/panoramas/untitledawdawdaw/pano_2.jpg',
      back: './assets/panoramas/untitledawdawdaw/pano_3.jpg',
      top: './assets/panoramas/untitledawdawdaw/pano_4.jpg',
      bottom: './assets/panoramas/untitledawdawdaw/pano_5.jpg',
    },
  },
  {
    id: 30,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'rynekzlotow',
    caption: 'Złotów - Stary Rynek',
    paths: {
      left: './assets/panoramas/rynekzlotow/pano_0.jpg',
      front: './assets/panoramas/rynekzlotow/pano_1.jpg',
      right: './assets/panoramas/rynekzlotow/pano_2.jpg',
      back: './assets/panoramas/rynekzlotow/pano_3.jpg',
      top: './assets/panoramas/rynekzlotow/pano_4.jpg',
      bottom: './assets/panoramas/rynekzlotow/pano_5.jpg',
    },
  },
  {
    id: 31,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'pierwsza_panorama',
    caption: 'Pierwsza panorama',
    paths: {
      left: './assets/panoramas/pierwsza_panorama/pano_0.jpg',
      front: './assets/panoramas/pierwsza_panorama/pano_1.jpg',
      right: './assets/panoramas/pierwsza_panorama/pano_2.jpg',
      back: './assets/panoramas/pierwsza_panorama/pano_3.jpg',
      top: './assets/panoramas/pierwsza_panorama/pano_4.jpg',
      bottom: './assets/panoramas/pierwsza_panorama/pano_5.jpg',
    },
  },
  {
    id: 32,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'untitled',
    caption: 'GDM 2021 - salka',
    paths: {
      left: './assets/panoramas/untitled/pano_0.jpg',
      front: './assets/panoramas/untitled/pano_1.jpg',
      right: './assets/panoramas/untitled/pano_2.jpg',
      back: './assets/panoramas/untitled/pano_3.jpg',
      top: './assets/panoramas/untitled/pano_4.jpg',
      bottom: './assets/panoramas/untitled/pano_5.jpg',
    },
  },
  {
    id: 33,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'plac_zabaw_duze_braki_w_obrazie',
    caption: 'Plac zabaw',
    paths: {
      left: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_0.jpg',
      front: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_1.jpg',
      right: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_2.jpg',
      back: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_3.jpg',
      top: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_4.jpg',
      bottom: './assets/panoramas/plac_zabaw_duze_braki_w_obrazie/pano_5.jpg',
    },
  },
  // {
  //   id: 34,
  // type: PanoramaTypeEnum.cubeFaces,
  //   rawTitle: 'pan1_aw',
  //   paths: {
  //     left: './assets/panoramas/pan1_aw/pano_0.jpg',
  //     front: './assets/panoramas/pan1_aw/pano_1.jpg',
  //     right: './assets/panoramas/pan1_aw/pano_2.jpg',
  //     back: './assets/panoramas/pan1_aw/pano_3.jpg',
  //     top: './assets/panoramas/pan1_aw/pano_4.jpg',
  //     bottom: './assets/panoramas/pan1_aw/pano_5.jpg',
  //   },
  // },
  {
    id: 35,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'eryk',
    caption: 'Eryk - nocne kino',
    paths: {
      left: './assets/panoramas/eryk/pano_0.jpg',
      front: './assets/panoramas/eryk/pano_1.jpg',
      right: './assets/panoramas/eryk/pano_2.jpg',
      back: './assets/panoramas/eryk/pano_3.jpg',
      top: './assets/panoramas/eryk/pano_4.jpg',
      bottom: './assets/panoramas/eryk/pano_5.jpg',
    },
  },
  // {
  //   id: 36,
  // type: PanoramaTypeEnum.cubeFaces,
  //   rawTitle: 'Panorama_Salon_wersja_light',
  //   caption: "BS - salon",
  //   paths: {
  //     left: './assets/panoramas/Panorama_Salon_wersja_light/pano_0.jpg',
  //     front: './assets/panoramas/Panorama_Salon_wersja_light/pano_1.jpg',
  //     right: './assets/panoramas/Panorama_Salon_wersja_light/pano_2.jpg',
  //     back: './assets/panoramas/Panorama_Salon_wersja_light/pano_3.jpg',
  //     top: './assets/panoramas/Panorama_Salon_wersja_light/pano_4.jpg',
  //     bottom: './assets/panoramas/Panorama_Salon_wersja_light/pano_5.jpg',
  //   },
  // },
  // {
  //   id: 37,
  //   type: PanoramaTypeEnum.equirectangular,
  //   title: 'untitled2a',
  //   paths: {
  //     left: './assets/panoramas/untitled2a/pano_0.jpg',
  //     front: './assets/panoramas/untitled2a/pano_1.jpg',
  //     right: './assets/panoramas/untitled2a/pano_2.jpg',
  //     back: './assets/panoramas/untitled2a/pano_3.jpg',
  //     top: './assets/panoramas/untitled2a/pano_4.jpg',
  //     bottom: './assets/panoramas/untitled2a/pano_5.jpg',
  //   },
  // },
  {
    id: 38,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'wersja_hi',
    caption: 'BS - salon',
    paths: {
      left: './assets/panoramas/wersja_hi/pano_0.jpg',
      front: './assets/panoramas/wersja_hi/pano_1.jpg',
      right: './assets/panoramas/wersja_hi/pano_2.jpg',
      back: './assets/panoramas/wersja_hi/pano_3.jpg',
      top: './assets/panoramas/wersja_hi/pano_4.jpg',
      bottom: './assets/panoramas/wersja_hi/pano_5.jpg',
    },
  },
  {
    id: 39,
    type: PanoramaTypeEnum.cubeFaces,
    rawTitle: 'chaber',
    caption: 'OW Chaber',
    paths: {
      left: './assets/panoramas/chaber/pano_0.jpg',
      front: './assets/panoramas/chaber/pano_1.jpg',
      right: './assets/panoramas/chaber/pano_2.jpg',
      back: './assets/panoramas/chaber/pano_3.jpg',
      top: './assets/panoramas/chaber/pano_4.jpg',
      bottom: './assets/panoramas/chaber/pano_5.jpg',
    },
  },
];
